### ISSUE TITLE
Veteran form submission fails if no mailchimp API key

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#153]
If there is no mailchimp API key or mailing list id set the `#create` method in `veterans_controller` will fail.

Steps to rep:
- Make sure MAILCHIMP_API_KEY is not set (`unset MAILCHIMP_API_KEY`)
- Visit /action
- Submit the form
- You should see a 500 error

This is probably pretty low priority.

```
2016-03-25T04:03:53.014423+00:00 app[web.1]: Completed 500 Internal Server Error in 1202ms (ActiveRecord: 8.7ms)
2016-03-25T04:03:53.022285+00:00 app[web.1]: F, [2016-03-25T04:03:53.022178 #3] FATAL -- :
2016-03-25T04:03:53.022301+00:00 app[web.1]:
2016-03-25T04:03:53.022297+00:00 app[web.1]: Gibbon::GibbonError (You must set an api_key prior to making a call):
2016-03-25T04:03:53.022298+00:00 app[web.1]:   app/models/veteran.rb:35:in `add_to_mailchimp'
2016-03-25T04:03:53.022299+00:00 app[web.1]:   app/controllers/veterans_controller.rb:34:in `block in create'
2016-03-25T04:03:53.022300+00:00 app[web.1]:   app/controllers/veterans_controller.rb:30:in `create'
```

This should probably just chuck an error or warning into the log and keep going.

**Comment by CdiegoBB** [comment]
Hey rickr, I am new with this and I have a question, when one found a bug is the same who repair it or anyone can do it.

**Comment by rickr** [comment]
Hi @CdiegoBB 

If no one has claimed a ticket (in the comments or via one of the Status labels) it's open for anyone to work on! If you'd like to claim this one let me know.
