### ISSUE TITLE
If a user signs up with an existing email the default rails error page is displayed

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#227]
Steps to rep:

* Visit https://operationcode.org/action
* Sign up with an email address
* Visit https://operationcode.org/action again
* Sign up with the same email address

You should see the default rails error: `We're sorry, but something went wrong.`

You should get a page that says something along the lines of 'this email has already been registered'.

Log entry: 

```
05-27T02:07:26.935634+00:00 app[web.1]: Completed 500 Internal Server Error in 3973ms (ActiveRecord: 2514.3ms)
2016-05-27T02:07:26.937849+00:00 app[web.1]: Gibbon::MailChimpError (the server responded with status 400 @title="Member Exists", @detail=" is already a list member. Use PUT to insert or update list members.", @body={"type"=>"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/", "title"=>"Member Exists", "status"=>400, "detail"=>" is already a list member. Use PUT to insert or update list members.", "instance"=>""}, @raw_body="{\"type\":\"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/\",\"title\":\"Member Exists\",\"status\":400,\"detail\":\" is already a list member. Use PUT to insert or update list members.\",\"instance\":\"\"}", @status_code=400):
2016-05-27T02:07:26.937850+00:00 app[web.1]:   app/models/veteran.rb:43:in `add_to_mailchimp'
2016-05-27T02:07:26.937851+00:00 app[web.1]:
2016-05-27T02:07:26.937851+00:00 app[web.1]:   app/controllers/veterans_controller.rb:31:in `create'
2016-05-27T02:07:26.937836+00:00 app[web.1]: F, [2016-05-27T02:07:26.937776 #3] FATAL -- :
```

**Comment by rickr** [comment]
This might have been fixed by moving the inviter to ActiveJob.

**Comment by rickr** [comment]
Devise has fixed this.
