### ISSUE TITLE
Gibbon::MailChimpError: the server responded with status 400 @title="Invalid Resource", @detail="The resource submitted c...

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#692]
https://sentry.io/operation-code/operation-code/issues/234697185/

I think this might be invalid input making it to the mailchimp inviter?
```
Faraday::ClientError: the server responded with status 400
  app/jobs/mailchimp_inviter_job.rb:7:in `perform'
    gibbon.lists(ENV['MAILCHIMP_LIST_ID']).members.create(
...
(76 additional frame(s) were not displayed)

Gibbon::MailChimpError: the server responded with status 400 @title="Invalid Resource", @detail="The resource submitted could not be validated. For field-specific details, see the 'errors' array.", @body={"type"=>"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/", "title"=>"Invalid Resource", "status"=>400, "detail"=>"The resource submitted could not be validated. For field-specific details, see the 'errors' array.", "instance"=>"", "errors"=>[{"field"=>"merge_fields.FNAME", "message"=>"Data did not match any of the schemas described in anyOf."}, {"field"=>"merge_fields.LNAME", "message"=>"Data did not match any of the schemas described in anyOf."}]}, @raw_body="{\"type\":\"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/\",\"title\":\"Invalid Resource\",\"status\":400,\"detail\":\"The resource submitted could not be validated. For field-specific details, see the 'errors' array.\",\"instance\":\"\",\"errors\":[{\"field\":\"merge_fields.FNAME\",\"message\":\"Data did not match any of the schemas described in anyOf.\"},{\"field\":\"merge_fields.LNAME\",\"message\":\"Data did not match any of the schemas described in anyOf.\"}]}", @status_code=400
  app/jobs/mailchimp_inviter_job.rb:7:in `perform'
    gibbon.lists(ENV['MAILCHIMP_LIST_ID']).members.create(
...
(71 additional frame(s) were not displayed)

the server responded with status 400 @title="Invalid Resource", @detail="The resource submitted could not be validated. For field-specific details, see the 'errors' array.", @body={"type"=>"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/", "title"=>"Invalid Resource", "status"=>400, "detail"=>"The resource submitted could not be validated. For field-specific details, see the 'errors' array.", "instance"=>"", "errors"=>[{"field"=>"merge_fields.FNAME", "message"=>"Data did not match any of the schemas described in anyOf."}, {"field"=>"merge_fields.LNAME", "message"=>"Data did not match any of the schemas described in anyOf."}]}, @raw_body="{\"type\":\"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/\",\"title\":\"Invalid Resource\",\"status\":400,\"detail\":\"The resource submitted could not be validated. For field-specific details, see the 'errors' array.\",\"instance\":\"\",\"errors\":[{\"field\":\"merge_fields.FNAME\",\"message\":\"Data did not match any of the schemas described in anyOf.\"},{\"field\":\"merge_fields.LNAME\",\"message\":\"Data did not match any of the schemas described in anyOf.\"}]}", @status_code=400
```

**Comment by sethbergman** [comment]
```"errors\":[{\"field\":\"merge_fields.FNAME\",\"message\":\"Data did not match any of the schemas described in anyOf.\"},{\"field\":\"merge_fields.LNAME\",\"message\":\```

It looks like the schema doesn't match the available field type, or maybe the `(ENV['MAILCHIMP_LIST_ID'])` is incorrect.

- http://kb.mailchimp.com/lists/manage-contacts/manage-list-and-signup-form-fields

- http://kb.mailchimp.com/lists/manage-contacts/manage-list-and-signup-form-fields#Add-a-Predefined-List-Field

We may need to merge some fields, or use a predefined set. I haven't looked too far into it yet.
